### Get all customers

GET http://localhost:5000/api/v1/customers
Content-Type: application/json

### Get customer with id

GET http://localhost:5000/api/v1/customer/1
Content-Type: application/json

### Create customer

POST http://localhost:5000/api/v1/customer
Content-Type: application/json

{
  "full_name": "K_5m8",
  "email": "test.k.v+5m8@gmail.com",
  "phone": "0931234567",
  "password": "qwerty",
  "createdAt": "2026-09-25T11:45:48.205Z",
  "updatedAt": "2026-09-25T11:45:48.205Z"
}

### UPDATE customer

PUT http://localhost:5000/api/v1/customer
Content-Type: application/json

{
  "id": 12,
  "full_name": "K_12",
  "email": "test.k.v+12@gmail.com",
  "phone": "0931234567",
  "password": "qwerty",
  "createdAt": "2026-09-25T11:45:48.205Z",
  "updatedAt": "2026-09-25T11:45:48.205Z"
}

### Delete customer with id

DELETE http://localhost:5000/api/v1/customer/12
Content-Type: application/json
